'use client';

import { useMemo, useState } from 'react';
import { Question, Vote } from '@/lib/types';
import { formatDecisionTime } from '@/lib/statistics';

export function DecisionMap({ votes, question }: { votes: Vote[]; userVote?: Vote | null; question: Question }) {
  const [hovered, setHovered] = useState<Vote | null>(null);
  const maxTime = Math.max(...votes.map(vote => vote.decisionTimeMs), 1000);
  const dots = useMemo(() => votes.filter((_, index) => index % 2 === 0 || votes[index].isUser).map((vote, index) => ({ vote, x: 8 + vote.decisionTimeMs / maxTime * 84, y: 92 - vote.confidence / 10 * 84, jitter: (index % 3 - 1) * .45 })), [votes, maxTime]);

  return <div className="border border-zinc-800 bg-zinc-900/20 p-4 sm:p-5"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start"><div><p className="font-mono text-[10px] tracking-[.18em] text-zinc-600">DECISION MAP</p><p className="mt-2 text-sm text-zinc-300">A quieter view of the crowd</p></div><div className="flex gap-4 font-mono text-[9px] text-zinc-500"><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-amber-400" />{question.optionA.title}</span><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-indigo-400" />{question.optionB.title}</span></div></div><div className="relative mt-6 aspect-[1.5] min-h-[260px] border-l border-b border-zinc-800"><span className="absolute left-2 top-2 font-mono text-[8px] uppercase tracking-wider text-zinc-700">High confidence</span><span className="absolute bottom-2 left-2 font-mono text-[8px] uppercase tracking-wider text-zinc-700">Low confidence</span><span className="absolute bottom-[-20px] left-1/2 font-mono text-[8px] uppercase tracking-wider text-zinc-700">Decision time &rarr;</span><span className="absolute left-[10%] top-[22%] font-mono text-[8px] uppercase tracking-wider text-zinc-700">Impulsive certainty</span><span className="absolute right-[6%] top-[22%] font-mono text-[8px] uppercase tracking-wider text-zinc-700">Thoughtful deliberation</span><span className="absolute bottom-[16%] left-[10%] font-mono text-[8px] uppercase tracking-wider text-zinc-700">Quick doubt</span><span className="absolute bottom-[16%] right-[6%] font-mono text-[8px] uppercase tracking-wider text-zinc-700">Hesitant certainty</span>{dots.map(({ vote, x, y, jitter }) => <button type="button" aria-label="Anonymous vote" key={vote.id} onMouseEnter={() => setHovered(vote)} onMouseLeave={() => setHovered(null)} className={`absolute h-1 w-1 rounded-full opacity-60 transition hover:z-10 hover:scale-[3] hover:opacity-100 ${vote.choice === 'A' ? 'bg-amber-400' : 'bg-indigo-400'} ${vote.isUser ? 'pulse-ring !h-3 !w-3 !bg-white !opacity-100' : ''}`} style={{ left: `${x}%`, top: `${y + jitter}%` }} />)}{hovered && <div className="pointer-events-none absolute right-3 top-3 z-20 border border-zinc-700 bg-zinc-950/95 px-3 py-2.5 text-xs shadow-2xl"><p className="font-mono text-zinc-300">{hovered.choice === 'A' ? question.optionA.title : question.optionB.title}</p><p className="mt-1.5 text-zinc-600">{hovered.confidence}/10 confidence · {formatDecisionTime(hovered.decisionTimeMs)}</p></div>}</div></div>;
}
